test: Fixed the compilation issue
The return value of write() function is ignored, causing the following
compiler error|warning with gcc version 5.4

error: ignoring return value of 'ssize_t write(int, const void*, size_t)'

Fix this by storing the return value of write() and return a test error in
case of failure.

Reported-by: Coverity CID=284605
Signed-off-by: Madhavan Krishnan <madhavan.krishnan@linaro.org>
Reviewed-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>